# Generated by Django 6.0.6 on 2026-07-07 10:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Four',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('statut', models.CharField(choices=[('marche', 'En marche'), ('arret', "À l'arrêt"), ('refection', 'En réfection')], default='marche', max_length=20)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='TypeBrique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('fournisseur_defaut', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Campagne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('cloturee', 'Clôturée')], default='en_cours', max_length=20)),
                ('four', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campagnes', to='core.four')),
            ],
            options={
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='SousTypeBrique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Ex. : ST-1, Position clé, Petit format...', max_length=100)),
                ('format', models.CharField(choices=[('droite', 'Droite'), ('cintree', 'Cintrée'), ('speciale', 'Spéciale')], default='droite', max_length=20)),
                ('longueur', models.DecimalField(decimal_places=2, help_text='mm', max_digits=10)),
                ('largeur', models.DecimalField(decimal_places=2, help_text='mm', max_digits=10)),
                ('hauteur', models.DecimalField(decimal_places=2, help_text='mm', max_digits=10)),
                ('poids_unitaire', models.DecimalField(decimal_places=3, help_text='kg', max_digits=10)),
                ('formule_calcul', models.TextField(help_text='Expression libre. Variables disponibles : diametre, longueur_zone, epaisseur, longueur, largeur, hauteur, taux_chute, PI. Ex : (PI * diametre * longueur_zone) / (largeur * hauteur) * (1 + taux_chute)')),
                ('taux_chute', models.DecimalField(decimal_places=4, default=0, help_text='Coefficient de perte à la découpe, ex. 0.08 pour 8%. 0 par défaut pour les sous-types droits.', max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('sous_types_lies', models.ManyToManyField(blank=True, help_text='Sous-types toujours utilisés ensemble avec celui-ci (ex. deux formes trapézoïdales X/Y alternées dans le même anneau). Relation symétrique : lier X à Y suffit, Y sera automatiquement lié à X.', to='core.soustypebrique')),
                ('type_brique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sous_types', to='core.typebrique')),
            ],
            options={
                'ordering': ['type_brique', 'nom'],
                'unique_together': {('type_brique', 'nom')},
            },
        ),
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_mouvement', models.CharField(choices=[('entree', 'Entrée'), ('sortie', 'Sortie'), ('ajustement', 'Ajustement (inventaire)')], max_length=10)),
                ('quantite', models.DecimalField(decimal_places=2, help_text='pièces (signée)', max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('reference', models.CharField(blank=True, help_text='Campagne ou bon de réception', max_length=150)),
                ('fournisseur_lot', models.CharField(blank=True, max_length=150)),
                ('motif', models.CharField(blank=True, help_text="Obligatoire pour un ajustement d'inventaire", max_length=255)),
                ('sous_type_brique', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mouvements', to='core.soustypebrique')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_actuelle', models.DecimalField(decimal_places=2, default=0, help_text='pièces', max_digits=10)),
                ('seuil_mini', models.DecimalField(decimal_places=2, default=0, help_text='pièces', max_digits=10)),
                ('sous_type_brique', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='core.soustypebrique')),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('diametre_nominal', models.DecimalField(decimal_places=2, help_text='mm (valeur de conception, ne change pas)', max_digits=10)),
                ('longueur', models.DecimalField(decimal_places=2, help_text='mm', max_digits=10)),
                ('position', models.PositiveIntegerField(help_text='Ordre / position dans le four')),
                ('four', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='core.four')),
                ('sous_type_brique_defaut', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zones_defaut', to='core.soustypebrique')),
                ('sous_types_brique_autorises', models.ManyToManyField(blank=True, help_text='Sous-types utilisables dans cette zone. Si vide, tous les sous-types sont proposés (à configurer).', related_name='zones_autorisees', to='core.soustypebrique')),
            ],
            options={
                'ordering': ['four', 'position'],
            },
        ),
        migrations.CreateModel(
            name='ConsommationReelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_posee', models.DecimalField(decimal_places=2, help_text='pièces', max_digits=10)),
                ('commentaire', models.TextField(blank=True, help_text='Anomalie éventuelle')),
                ('date_saisie', models.DateTimeField(auto_now_add=True)),
                ('campagne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consommations', to='core.campagne')),
                ('sous_type_brique', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consommations', to='core.soustypebrique')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consommations', to='core.zone')),
            ],
            options={
                'ordering': ['-date_saisie'],
            },
        ),
        migrations.AddField(
            model_name='campagne',
            name='zones',
            field=models.ManyToManyField(related_name='campagnes', to='core.zone'),
        ),
        migrations.CreateModel(
            name='BesoinTheorique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diametre_utilise', models.DecimalField(decimal_places=2, help_text='mm (mesuré)', max_digits=10)),
                ('epaisseur_garnissage_utilisee', models.DecimalField(decimal_places=2, help_text='mm', max_digits=10)),
                ('quantite_calculee', models.DecimalField(decimal_places=2, help_text='pièces, avec dérive (mesure réelle)', max_digits=10)),
                ('quantite_calculee_nominale', models.DecimalField(decimal_places=2, help_text='pièces, sans dérive (diamètre nominal de la zone)', max_digits=10)),
                ('campagne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='besoins', to='core.campagne')),
                ('sous_type_brique', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='besoins', to='core.soustypebrique')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='besoins', to='core.zone')),
            ],
            options={
                'ordering': ['campagne', 'zone'],
                'unique_together': {('campagne', 'zone', 'sous_type_brique')},
            },
        ),
    ]
