# Generated by Django 6.0.7 on 2026-07-08 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120, unique=True)),
                ('expression', models.TextField(help_text='Variables disponibles : diametre, longueur_zone, epaisseur, longueur, largeur, hauteur, taux_chute, PI.')),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.AlterField(
            model_name='soustypebrique',
            name='formule_calcul',
            field=models.TextField(blank=True, help_text='Expression libre. Variables disponibles : diametre, longueur_zone, epaisseur, longueur, largeur, hauteur, taux_chute, PI. Ex : (PI * diametre * longueur_zone) / (largeur * hauteur) * (1 + taux_chute)'),
        ),
        migrations.AddField(
            model_name='soustypebrique',
            name='formule_predefinie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sous_types', to='core.formule'),
        ),
        migrations.AddField(
            model_name='typebrique',
            name='formule_sous_type_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='types_briques_st1', to='core.formule'),
        ),
        migrations.AddField(
            model_name='typebrique',
            name='formule_sous_type_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='types_briques_st2', to='core.formule'),
        ),
        migrations.AddField(
            model_name='typebrique',
            name='formule_sous_type_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='types_briques_st3', to='core.formule'),
        ),
        migrations.AddField(
            model_name='typebrique',
            name='formule_sous_type_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='types_briques_st4', to='core.formule'),
        ),
    ]
